import "./router";
import "./pages/home/index";
import "./pages/login/index";
import "./pages/signin/index";
import "./pages/rooms/index";
import "./pages/new-room/index";
import "./pages/existing-room/index";
import "./pages/instructions/index";
import "./pages/game/index";
